version: '3.3'
services:

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram-app
    image: mrzoom007/foodgram_back:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    restart: always

  frontend:
    image: mrzoom007/foodgram_front:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend

  gateway:
    depends_on:
      - backend
      - frontend
    image: mrzoom007/foodgram_gateway
    env_file: .env
    ports:
      - 8002:80
    volumes:
      - static:/static/
      - media:/app/media
    restart: always
