# Generated by Django 4.2.13 on 2024-12-29 11:52

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.combined_username_validator], verbose_name='Логин'),
        ),
    ]
